// <auto-generated />
using System;
using Convertarr.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Convertarr.Data.Migrations
{
    [DbContext(typeof(ConvertarrContext))]
    [Migration("20230213211154_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("Convertarr.Data.MediaFile", b =>
                {
                    b.Property<int>("MediaFileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastScanned")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastWrite")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MediaInfoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MediaFileId");

                    b.HasIndex("MediaInfoId");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("Convertarr.Data.Models.AudioStream", b =>
                {
                    b.Property<int>("AudioStreamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("Bitrate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Channels")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codec")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Default")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Forced")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("MediaInfoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaStreamType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SampleRate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AudioStreamId");

                    b.HasIndex("MediaInfoId");

                    b.ToTable("AudioStream");
                });

            modelBuilder.Entity("Convertarr.Data.Models.MediaInfo", b =>
                {
                    b.Property<int>("MediaInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("TEXT");

                    b.HasKey("MediaInfoId");

                    b.ToTable("MediaInfo");
                });

            modelBuilder.Entity("Convertarr.Data.Models.SubtitleStream", b =>
                {
                    b.Property<int>("SubtitleStreamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codec")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Default")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Forced")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("MediaInfoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaStreamType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SubtitleStreamId");

                    b.HasIndex("MediaInfoId");

                    b.ToTable("SubtitleStream");
                });

            modelBuilder.Entity("Convertarr.Data.Models.VideoStream", b =>
                {
                    b.Property<int>("VideoStreamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("Bitrate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codec")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Default")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Forced")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Framerate")
                        .HasColumnType("REAL");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MediaInfoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaStreamType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PixelFormat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ratio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Rotation")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("VideoStreamId");

                    b.HasIndex("MediaInfoId");

                    b.ToTable("VideoStream");
                });

            modelBuilder.Entity("Convertarr.Data.MediaFile", b =>
                {
                    b.HasOne("Convertarr.Data.Models.MediaInfo", "MediaInfo")
                        .WithMany()
                        .HasForeignKey("MediaInfoId");

                    b.Navigation("MediaInfo");
                });

            modelBuilder.Entity("Convertarr.Data.Models.AudioStream", b =>
                {
                    b.HasOne("Convertarr.Data.Models.MediaInfo", null)
                        .WithMany("AudioStreams")
                        .HasForeignKey("MediaInfoId");
                });

            modelBuilder.Entity("Convertarr.Data.Models.SubtitleStream", b =>
                {
                    b.HasOne("Convertarr.Data.Models.MediaInfo", null)
                        .WithMany("SubtitleStreams")
                        .HasForeignKey("MediaInfoId");
                });

            modelBuilder.Entity("Convertarr.Data.Models.VideoStream", b =>
                {
                    b.HasOne("Convertarr.Data.Models.MediaInfo", null)
                        .WithMany("VideoStreams")
                        .HasForeignKey("MediaInfoId");
                });

            modelBuilder.Entity("Convertarr.Data.Models.MediaInfo", b =>
                {
                    b.Navigation("AudioStreams");

                    b.Navigation("SubtitleStreams");

                    b.Navigation("VideoStreams");
                });
#pragma warning restore 612, 618
        }
    }
}
